# Site settings
title: Beautiful Burmese Typography
email: emoosx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Beautiful Burmese Typography
baseurl: "/beautiful-burmese-type/" # the subpath of your site, e.g. /blog/
url: "http://khzaw.github.io"
twitter_username: khzaw
github_username:  khzaw

# Build settings
markdown: kramdown